- name: add group
  group: name=webadmin state=present

- name: add user
  user: name=webadmin shell=/bin/bash group=webadmin groups=nginx

- name: add user key
  authorized_key: user=webadmin
              key="{{ lookup('file','webadmin_pem.pub') }}"

- name: public_html dir
  file: path=/home/webadmin/public_html state=directory owner=webadmin group=webadmin mode=0775

- name: modify homedir
  file: path=/home/webadmin state=directory mode=0755
